# Generated by Django 4.2.2 on 2023-06-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooksapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
